#!/bin/sh
INSTALL_LOG="buildlog.install"
ERROR_LOG="buildlog.error"
echo $(date) >>"$INSTALL_LOG"
echo $(date) >>"$ERROR_LOG"
echo "=========================================="
echo "Build tools" | tee -a "$INSTALL_LOG" | tee -a "$ERROR_LOG"
time ./build.sh -U -u -O ~/obj -x -X ../xsrc -j 12 -m amd64 tools 1>>"$INSTALL_LOG" 2>>"$ERROR_LOG"
echo "Build kernel" | tee -a "$INSTALL_LOG" | tee -a "$ERROR_LOG"
time ./build.sh -U -u -O ~/obj -x -X ../xsrc -j 12 -m amd64 kernel=DEBUG 1>"$INSTALL_LOG" 2>>"$ERROR_LOG"
echo "Build userland" | tee -a "$INSTALL_LOG" | tee -a "$ERROR_LOG"
time ./build.sh -U -u -O ~/obj -x -X ../xsrc -j 12 -m amd64 release 1>"$INSTALL_LOG" 2>>"$ERROR_LOG"
echo "=========================================="
echo "Error Log:"
cat "$ERROR_LOG"
